defaults:
  - _self_
  - optimizer: lr0.003_gamma0.25
  - dataset: la
  - model: ibgnn
  - embedding: none

#### Experiment params ########################################################
hydra:
  run:
    dir: logs/${model.name}/${dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${model.name}/${dataset.name}/${hydra.job.num}

workers: 0
num_threads: 1
seed: 34

#### Training params ##########################################################
epochs: 300
patience: 35
batch_size: 64
train_batches: 1.0
grad_clip_val: 5
scale_axis: graph
add_exogenous: True

regularization_weight: 1.0

embedding:
  override method: uniform
  emb_size: 32
  
